# Generated by Django 4.2.20 on 2025-05-07 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_productmodel_product_view'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitemmodel',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='shop.productcolorinventory'),
            preserve_default=False,
        ),
    ]
