# Generated by Django 4.2.21 on 2025-05-09 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartitemmodel_color_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitemmodel',
            name='color_inventory',
        ),
    ]
