# Generated by Django 4.2.20 on 2025-05-07 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_productmodel_product_view'),
        ('cart', '0004_alter_cartitemmodel_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitemmodel',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.productcolorinventory'),
        ),
    ]
