# Generated by Django 4.2.23 on 2025-06-23 14:08

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_tags_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
