# Generated by Django 4.2.23 on 2025-07-16 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_productmodel_status'),
        ('blog', '0010_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_products', to='blog.post')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_products', to='shop.productmodel')),
            ],
            options={
                'verbose_name': 'پست محصول',
                'verbose_name_plural': 'پست محصولات',
            },
        ),
    ]
