FROM python:3.10

LABEL maintainer="programmer.amirrezaattary@gmail.com"
ENV PYTHONUNBUFFERED=1

# نصب ابزارهای مورد نیاز برای اجرای Google Chrome Headless
RUN apt-get update && apt-get install -y \
    wget \
    curl \
    unzip \
    gnupg \
    ca-certificates \
    fonts-liberation \
    libappindicator3-1 \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libcups2 \
    libdbus-1-3 \
    libgdk-pixbuf2.0-0 \
    libnspr4 \
    libnss3 \
    libx11-xcb1 \
    libxcomposite1 \
    libxdamage1 \
    libxrandr2 \
    xdg-utils \
    libgbm1 \
    libgtk-3-0 \
    libxshmfence1 \
    libxcb1 \
    libx11-6 \
    --no-install-recommends

# نصب Google Chrome
RUN wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
    && apt install -y ./google-chrome-stable_current_amd64.deb \
    && rm google-chrome-stable_current_amd64.deb

# نصب نیازمندی‌های پایتون
WORKDIR /usr/src/app
COPY ./requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY ./core .
