# Base image
FROM python:3.10-slim-buster

LABEL maintainer="programmer.amirrezaattary@gmail.com"

# Environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set work directory
WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --default-timeout=350 -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/

# Copy app files
COPY ./core /app/

# جمع‌آوری static files
# (STATIC_ROOT باید در settings.py روی `/app/staticfiles` تنظیم شده باشد)
RUN python manage.py collectstatic --noinput

# Expose gunicorn port
EXPOSE 8000

# Start gunicorn
# توجه: `core.wsgi` را با ماژول مناسب خودت جایگزین کن
CMD ["gunicorn", "core.wsgi", "--bind", "0.0.0.0:8000"]
