# Base image
FROM python:3.10-slim-buster

LABEL maintainer="programmer.amirrezaattary@gmail.com"

# Environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set work directory
WORKDIR /app

# نصب Chrome Headless و وابستگی‌ها
RUN apt-get update && apt-get install -y \
    wget \
    curl \
    unzip \
    gnupg \
    ca-certificates \
    fonts-liberation \
    libappindicator3-1 \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libcups2 \
    libdbus-1-3 \
    libgdk-pixbuf2.0-0 \
    libnspr4 \
    libnss3 \
    libx11-xcb1 \
    libxcomposite1 \
    libxdamage1 \
    libxrandr2 \
    xdg-utils \
    libgbm1 \
    libgtk-3-0 \
    libxshmfence1 \
    libxcb1 \
    libx11-6 \
    gcc \
    libpq-dev \
    --no-install-recommends \
    && wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
    && apt install -y ./google-chrome-stable_current_amd64.deb \
    && rm google-chrome-stable_current_amd64.deb \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --default-timeout=350 -r requirements.txt

# Copy app files
COPY ./core /app/

# جمع‌آوری static files
# (STATIC_ROOT باید در settings.py روی `/app/staticfiles` تنظیم شده باشد)
RUN python manage.py collectstatic --noinput

# Expose gunicorn port
EXPOSE 8000

# Start gunicorn
# توجه: `core.wsgi` را با ماژول مناسب خودت جایگزین کن
CMD ["gunicorn", "core.wsgi", "--bind", "0.0.0.0:8000"]
