# Generated by Django 4.2.23 on 2025-07-18 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0002_aboutgrop_alter_contact_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='تایتل')),
                ('video', models.FileField(upload_to='stories/videos/', verbose_name='فیلم')),
                ('icon', models.ImageField(upload_to='stories/icons/', verbose_name='آیکون استوری')),
                ('status', models.IntegerField(choices=[(1, 'در انتظار تایید'), (2, 'تایید شده'), (3, 'رد شده')], default=1, verbose_name='آیکون استوری')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'استوری',
                'verbose_name_plural': 'استوری\u200cها',
            },
        ),
    ]
