# Generated by Django 4.2.23 on 2025-07-26 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_story'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-created_at'], 'verbose_name': 'استوری', 'verbose_name_plural': 'استوری\u200cها'},
        ),
    ]
