"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""



from pathlib import Path
from decouple import config
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/
DEBUG = True

# SECURITY WARNING: keep the secret key used in production secret!
ALLOWED_HOSTS = [
    '192.168.73.237',
    '127.0.0.1',
    'manmarket.ir',
    'www.manmarket.ir',
    'mail.manmarket.ir',
    "https://manmarket.ir",
    "https://www.manmarket.ir",
    "https://mail.manmarket.ir",  # ← این خط را اضافه کن
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

CSRF_TRUSTED_ORIGINS = [
    "https://manmarket.ir",
    "https://www.manmarket.ir",
    "https://mail.manmarket.ir",# اگر از www هم استفاده می‌کنی
]
"""https://api.digikala.com/v1/rate-review/products/18132558/"""

SECRET_KEY = 'django-insecure-jc35qo)gv(idt+zlq=2&!yq%y)twxum-$8@s^#3dj^7n^!yn_e'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'django.contrib.sites',
    
    # created my app
    'app.website',
    'app.accounts',
    'app.shop',
    'app.cart',
    'app.blog',
    'app.order',
    'app.dashboard',
    'app.payment',
    'app.pricegethamrh',
    'app.getspecification',
    'app.faq',
    'app.review',
    'app.wallets',
    'app.chat',
    
    # rest api apps
    'rest_framework',
    "django_filters",
    "corsheaders",
    
    
    # other app for internet
    'channels',
    'django.contrib.humanize',
    "taggit",
    "django_jalali",
    'jalali_date',
    'robots',
    # 'django_celery_beat',
    'django_summernote', 
    
    # api doc
    'drf_yasg',

]


SITE_ID = 2

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware", 
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'app.accounts.middleware.restrict_admin.RestrictAdminMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'app.cart.context_processors.cart_processor',
                'app.shop.context_processors.wishlist_total_items',
                'app.shop.context_processors.brand_list_image',
                'app.shop.context_processors.category_list_image',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            'timeout': 60,  # در ثانیه (افزایش timeout پیش‌فرض)
        }
    }
}
 

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tehran'


USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "static"


MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

STATICFILES_DIRS = [
    BASE_DIR / "staticfiles",
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.c1.liara.email'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'fervent_feistel_3t4mtv'
EMAIL_HOST_PASSWORD = 'efb1e7b5-d4e6-4c88-bc10-b473da168442'
EMAIL_USE_TLS = True

DEFAULT_FROM_EMAIL = 'info@manmarket.ir'
SERVER_EMAIL = 'info@manmarket.ir'



SHOW_DEBUGGER_TOOLBAR = config("SHOW_DEBUGGER_TOOLBAR", cast=bool, default=True)
if SHOW_DEBUGGER_TOOLBAR:
    INSTALLED_APPS += [
        "debug_toolbar",
    ]
    MIDDLEWARE += [
        "debug_toolbar.middleware.DebugToolbarMiddleware",
    ]
    import socket  # only if you haven't already imported this
    hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
    INTERNAL_IPS = [ip[: ip.rfind(".")] + ".1" for ip in ips] + ["127.0.0.1", "10.0.2.2"]


AUTH_USER_MODEL = 'accounts.User'
LOGIN_REDIRECT_URL = 'dashboard:home'
LOGOUT_REDIRECT_URL= '/'


# sms.ir webservice
SMSAPIKEY = "co6QLJNKUrO0x75n94cWToUcFxsD4TEQGaiNXqlhR9THVrh6B5bBdXDayfe0asCb"
SMSLINENUMBER = "30004007672729"


# payment gateway settings

# zarinpal client
MERCHANT_ID = config("MERCHANT_ID",default="0db95e76-ee4f-4546-a86e-7c12c95e662b")
SANDBOX_MODE = config("SANDBOX_MODE", cast=bool, default=True)

# gsmpay client
GSMPAY_MERCHANT_CODE = config("GSMPAY_MERCHANT_CODE",default="1f8c54e2-6bd2-4acf-b54c-cedce1ef942b")

# refah client
REFAH_USERNAME = "70072831"
REFAH_PASSWORD = "PF%cv-GI"
REFAH_TERMINAL = 70072831



# change time for active token password-reset 

PASSWORD_RESET_TIMEOUT_DAYS = 2



# CSRF_COOKIE_SECURE = True

# celery settings

# CELERY_BROKER_URL = "redis://redis:6379/0"
# CELERY_RESULT_BACKEND = 'redis://redis:6379/3'

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    }
}


# CACHES = {
#     "default": {
#         "BACKEND": "django_redis.cache.RedisCache",
#         "LOCATION": "redis://redis:6379/1",
#         "OPTIONS": {
#             "CLIENT_CLASS": "django_redis.client.DefaultClient",
#         }
#     }
# }


# time setting

DATA_UPLOAD_MAX_NUMBER_FIELDS = 50000


# API SETTINGS
CORS_ALLOW_ALL_ORIGINS = True


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),  # ← مدت زمان Access Token
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),     # ← مدت زمان Refresh Token
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

SAMAN_TERMINAL_ID = 14315215