# Generated by Django 4.2.23 on 2025-08-05 15:28

import app.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_profile_first_name_alter_profile_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[app.accounts.validators.validate_iranian_cellphone_number]),
        ),
    ]
