# Generated by Django 4.2.23 on 2025-08-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_profile_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.CharField(blank=True, help_text='تاریخ تولد را وارد کنید (مثلاً 1375-05-10)', max_length=10, null=True),
        ),
    ]
