# Generated by Django 4.2.23 on 2025-09-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_otp_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code_melli',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
