# Generated by Django 4.2.26 on 2025-12-01 06:45

import app.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_user_code_melli'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-phone_number']},
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='09000000000', max_length=12, unique=True, validators=[app.accounts.validators.validate_iranian_cellphone_number]),
            preserve_default=False,
        ),
    ]
