# Generated by Django 4.2.21 on 2025-05-09 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_productmodel_product_view'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitemmodel',
            name='color',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.PROTECT, to='shop.color'),
            preserve_default=False,
        ),
    ]
