# Generated by Django 4.2.21 on 2025-05-09 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_productmodel_product_view'),
        ('cart', '0002_alter_cartitemmodel_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitemmodel',
            name='color_inventory',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.PROTECT, to='shop.productcolorinventory'),
            preserve_default=False,
        ),
    ]
