# Generated by Django 4.2.21 on 2025-05-09 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_productmodel_product_view'),
        ('cart', '0004_remove_cartitemmodel_color_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitemmodel',
            name='color_inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.productcolorinventory'),
        ),
    ]
