# Generated by Django 4.2.20 on 2025-05-10 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_productmodel_product_view'),
        ('cart', '0005_cartitemmodel_color_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitemmodel',
            name='color_inventory',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.PROTECT, to='shop.productcolorinventory'),
            preserve_default=False,
        ),
    ]
