# Generated by Django 4.2.23 on 2025-06-22 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_ordermodel_tracking_code'),
        ('wallets', '0002_alter_wallettransaction_transaction_type'),
        ('payment', '0002_remove_paymentmodel_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.ordermodel'),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallets.wallet'),
        ),
    ]
