# Generated by Django 4.2.23 on 2025-07-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_paymentmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='payemnt_type',
            field=models.IntegerField(choices=[(1, 'پرداخت با کارت بانکی'), (2, 'پرداخت با کیف پول'), (3, 'پرداخت در محل')], default=1),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='remainder',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
