# Generated by Django 4.2.23 on 2025-07-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_paymentmodel_payemnt_type_paymentmodel_remainder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='payemnt_type',
            field=models.IntegerField(choices=[(1, 'پرداخت با کارت بانکی'), (2, 'پرداخت با کیف پول'), (3, 'پرداخت در محل'), (4, 'ترکیبی کیف پول و کارت')], default=1),
        ),
    ]
