# Generated by Django 4.2.23 on 2025-07-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_first_name_alter_profile_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, help_text='تاریخ تولد را وارد کنید (مثلاً 1375-05-10)', null=True),
        ),
    ]
