# Generated by Django 4.2.23 on 2025-08-11 16:21

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_emailotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
