# Generated by Django 4.2.19 on 2025-04-05 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_productcolorvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='color',
        ),
    ]
