# Generated by Django 4.2.20 on 2025-04-27 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_productspecifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspecifications',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productcolor',
            name='hex_value',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='stock',
        ),
        migrations.AddField(
            model_name='productcolor',
            name='discount_percent',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ProductColorVariant',
        ),
        migrations.DeleteModel(
            name='ProductSpecifications',
        ),
    ]
