# Generated by Django 4.2.20 on 2025-04-27 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_productspecifications_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolor',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='shop.productmodel'),
        ),
    ]
