# Generated by Django 4.2.20 on 2025-04-27 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_productcolor_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='product',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='shop.productmodel'),
            preserve_default=False,
        ),
    ]
