# Generated by Django 4.2.21 on 2025-06-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_productmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolorinventory',
            name='hex_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
