# Generated by Django 4.2.23 on 2025-06-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_wishlistproductmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, default='default/brand.webp', null=True, upload_to='brand/img/'),
        ),
    ]
