# Generated by Django 4.2.23 on 2025-06-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_brand_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='brief_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
