# Generated by Django 4.2.23 on 2025-07-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_productmodel_warranty'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolorinventory',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
