# Generated by Django 4.2.23 on 2025-07-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_productcolorinventory_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspecification',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
