# Generated by Django 4.2.23 on 2025-07-20 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_megamenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='megamenu',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.brand'),
            preserve_default=False,
        ),
    ]
