# Generated by Django 4.2.23 on 2025-07-26 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_megamenu_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['-id']},
        ),
    ]
