# Generated by Django 4.2.23 on 2025-08-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_alter_productcategorymodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
