# Generated by Django 4.2.23 on 2025-08-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_alter_wishlistproductmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecification',
            name='value',
            field=models.CharField(max_length=600),
        ),
    ]
