# Generated by Django 4.2.23 on 2025-08-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_alter_productspecification_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolorinventory',
            name='hex_color',
            field=models.CharField(default='#000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='value',
            field=models.CharField(max_length=1000),
        ),
    ]
