# Generated by Django 4.2.20 on 2025-05-10 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderitemmodel_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'ordering': ['-created_date']},
        ),
    ]
