# Generated by Django 4.2.26 on 2025-12-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_ordermodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddressmodel',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='useraddressmodel',
            name='phone_number',
            field=models.CharField(default='', max_length=250),
        ),
    ]
