# Generated by Django 4.2.26 on 2025-12-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_useraddressmodel_name_useraddressmodel_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='phone_number',
            field=models.CharField(default='', max_length=250),
        ),
    ]
