# Generated by Django 4.2.26 on 2025-12-18 09:06

import app.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_ordermodel_name_ordermodel_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddressmodel',
            name='phone_number',
            field=models.CharField(default='', max_length=12, validators=[app.accounts.validators.validate_iranian_cellphone_number]),
        ),
    ]
