# Generated by Django 4.2.23 on 2025-07-14 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_productspecification_status'),
        ('getspecification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricespecification',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricespecification', to='shop.productmodel'),
        ),
    ]
