# Generated by Django 4.2.23 on 2025-08-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatroom_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.UniqueConstraint(fields=('product', 'customer'), name='unique_product_customer_chat'),
        ),
    ]
