# Generated by Django 4.2.20 on 2025-04-29 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_brand_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.brand'),
        ),
    ]
