# Generated by Django 4.2.20 on 2025-04-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_productmodel_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='product_view',
            field=models.IntegerField(default=0),
        ),
    ]
