# Generated by Django 4.2.21 on 2025-05-15 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_productmodel_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimagemodel',
            options={'ordering': ['created_date']},
        ),
    ]
