# Generated by Django 4.2.21 on 2025-05-27 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_productimagemodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimagemodel',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='shop.color'),
        ),
    ]
