# Generated by Django 4.2.22 on 2025-06-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_productimagemodel_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(default='default/product-image.png', upload_to='product/img/'),
        ),
    ]
