# Generated by Django 4.2.23 on 2025-06-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_productcolorinventory_hex_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolorinventory',
            name='hex_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
