# Generated by Django 4.2.23 on 2025-06-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_productmodel_brief_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='sales_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
