# Generated by Django 4.2.23 on 2025-06-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_productmodel_sales_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategorymodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/img/'),
        ),
    ]
