# Generated by Django 4.2.23 on 2025-06-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_productcategorymodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='warranty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
