# Generated by Django 4.2.23 on 2025-08-02 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_alter_color_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategorymodel',
            options={'ordering': ['created_date']},
        ),
    ]
