# Generated by Django 4.2.24 on 2025-09-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_alter_productcolorinventory_hex_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='hex_color',
            field=models.CharField(default='#000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='productcolorinventory',
            name='hex_color',
            field=models.CharField(default='#000000', max_length=20),
        ),
    ]
