# Generated by Django 4.2.24 on 2025-09-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_color_hex_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolorinventory',
            name='final_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
