# Generated by Django 4.2.24 on 2025-09-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_productcolorinventory_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
