# Generated by Django 4.2.26 on 2025-12-06 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_productmodel_meta_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='user',
        ),
    ]
