# Generated by Django 4.2.23 on 2025-06-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_ordermodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد رهگیری پستی'),
        ),
    ]
