# Generated by Django 4.2.23 on 2025-07-21 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_megamenu_brand'),
        ('order', '0007_ordermodel_tracking_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productmodel'),
        ),
    ]
