# Generated by Django 4.2.23 on 2025-08-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_ordermodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='tracking_type',
            field=models.IntegerField(choices=[(1, 'ارسال با پست عادی'), (2, 'ارسال با ماهکس'), (3, 'ارسال با تیپاکس'), (4, 'حضوری')], default=1),
        ),
    ]
