# Generated by Django 4.2.23 on 2025-08-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_ordermodel_tracking_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'در انتظار پرداخت'), (2, 'در انتظار تایید سفارش'), (3, 'در حال پردازش'), (4, 'ارسال شده'), (5, 'تحویل شده'), (6, 'لغو شده')], default=1),
        ),
    ]
