# Generated by Django 4.2.23 on 2025-08-11 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_alter_productcolorinventory_hex_color_and_more'),
        ('website', '0004_alter_story_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productmodel'),
        ),
    ]
