# Generated by Django 4.2.23 on 2025-08-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_story_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='title_product',
            field=models.CharField(default='لینک محصول', max_length=255),
        ),
    ]
