# Generated by Django 4.2.23 on 2025-07-31 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_paymentmodel_payemnt_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='payemnt_type',
            field=models.IntegerField(choices=[(1, 'پرداخت با درگاه پرداخت '), (2, 'پرداخت با کیف پول'), (3, 'پرداخت در محل'), (4, 'ترکیبی کیف پول و درگاه'), (5, 'پرداخت حضوری')], default=1),
        ),
    ]
