# Generated by Django 4.2.26 on 2025-11-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_paymentmodel_payemnt_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='payemnt_type',
            field=models.IntegerField(choices=[(1, 'پرداخت با درگاه پرداخت '), (2, 'پرداخت با کیف پول'), (3, 'پرداخت در محل'), (4, 'ترکیبی کیف پول و درگاه'), (5, 'پرداخت اقساطی با جی اس ام'), (6, 'پرداخت حضوری'), (7, 'پرداخت با درگاه بانک رفاه')], default=1),
        ),
    ]
