# Generated by Django 4.2.23 on 2025-07-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getspecification', '0003_alter_pricespecification_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricespecification',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
