# Generated by Django 4.2.26 on 2025-12-21 07:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getspecification', '0004_alter_pricespecification_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricespecification',
            name='number_comments',
            field=models.IntegerField(blank=True, default=10, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
