# Generated by Django 4.2.26 on 2025-12-21 07:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getspecification', '0005_pricespecification_number_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricespecification',
            name='number_comments',
            field=models.IntegerField(blank=True, default=10, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
