# Generated by Django 4.2.23 on 2025-07-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricegethamrh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricegethamrh',
            name='url_kasra',
            field=models.URLField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
