# Generated by Django 4.2.23 on 2025-08-12 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricegethamrh', '0002_pricegethamrh_url_kasra'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricegethamrh',
            name='discount_percent_product',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
