# Generated by Django 4.2.23 on 2025-08-12 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricegethamrh', '0003_pricegethamrh_discount_percent_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricegethamrh',
            name='discount_percent_product',
        ),
    ]
