# Generated by Django 4.2.24 on 2025-09-19 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricegethamrh', '0004_remove_pricegethamrh_discount_percent_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricegethamrh',
            name='profit',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
