# Generated by Django 4.2.20 on 2025-09-03 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_alter_productcolorinventory_hex_color_and_more'),
        ('review', '0002_alter_reviewmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.productmodel'),
        ),
    ]
