# Generated by Django 4.2.26 on 2025-11-22 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0003_alter_reviewmodel_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviw_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
