# Generated by Django 4.2.26 on 2025-12-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_alter_reviewmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
