# Generated by Django 4.2.26 on 2025-12-21 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_reviewmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
