# Generated by Django 4.2.21 on 2025-06-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('charge', 'شارژ'), ('withdraw', 'برداشت'), ('payment', 'پرداخت'), ('refund', 'برگشت وجه')], max_length=10),
        ),
    ]
